### ISSUE TITLE
New parameters suggestion to fix the unknown IIA ID of the partner that is sending the approval CNR

### ISSUE THREAD

**Issue by sascoms** [erasmus-without-paper/ewp-specs-api-iia-approval-cnr#2]
I guess all of us are aware and know the problem in the below IIA scenario:

1. HEI A creates an IIA ID: A111
2. HEI A sends IIA-CNR to HEI B for this IIA
3. HEI B receives CNR. 
4. HEI B imports this IIA (HEI A IIA ID A111)
5. HEI B agrees with conditions.
6. HEI B sends IIA Approval CNR to HEI A
7. HEI A receives IIA Approval CNR from HEI B
8. HEI B wants to send IIA Approval CNR to HEI A. 
-ENDS
and we are stuck here in the exchange/approval process.

HEI B either contacts HEI A via email or similar and tells them they need to send first an IIA CNR before the Approval CNR. So, HEI A knows HEI B's IIA ID. And this way, they can too send their approval to HEI B.

Now, we as erasmusjet do not allow sending approval CNRs without sending first an IIA CNR.
And as well as I know, dashboard first sends an IIA CNR before its approval CNR.

Both are workarounds. But we need real solutions for this issue.

And we think this can be solved by changing 1 and adding 1 new parameter to the Approval CNR.
REF: https://github.com/erasmus-without-paper/ewp-specs-api-iia-approval-cnr#request-parameters

Our suggestion is:
- approving_hei_id (required) [stays as is]
- owner_hei_id (required) [stays as is]
- **iia_id (required) [rename to owner_hei_iia_id and still required]**
- **(new parameter) approving_hei_iia_id and as required**

This way, the receiver HEI of the approval CNR will know the cnr sender HEI's IIA ID and will save it and then sends an approval CNR.

We also offer to put a deadline for this change to be applied by all providers, once accepted and merged into a new version.

**Comment by kamil-olszewski-uw** [comment]
The approving_hei_iia_id parameter could not be required, because not always in both systems the agreements will be in a 1:1 relationship and not always the approval will be mutual (see: erasmus-without-paper/ewp-specs-api-iias#66).

Indeed, in your example in step 8, HEI A does not know what code the copy of its IIA has in HEI B's system. However, if HEI A did get approval for its IIA but did not receive the IIAs CNR, then HEI A realizes that HEI B was processing the IIA in some way. HEI A can then send HEI B IIAs index request and IIAs get request (without waiting for B's IIAs CNR request) to check if HEI B has its own copy of IIA.
